# .github/workflows/static-analysis.yml
name: Python Static Analysis

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  python_static_analysis:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Prepare environment
        run: |
          python3 --version
          pip --version
          python3 -m pip install --upgrade pip
          pip install -e .[test,docs]

      - name: Run linters / static checks
        run: |
          codespell || true
          mypy . || true
          bandit -r . || true
          vulture . || true
          ruff check || true
          ty check || true
